feat: increase transparency using checkboxes disclaimers
deltaDAO/mvg-portal pull request #182
Opened 2022-08-12 17:47 UTC by LucaMilanese90

Fixes #177

## Proposed Changes

  - add checkboxes before publish
  - add disclaimer under asset buy button

2022-08-12 18:39 UTC, moritzkirstein requested changes

2022-08-12 18:39 UTC, moritzkirstein commented on src/components/atoms/ButtonBuy.tsx
> +            />
question(blocking): Can we query this from our content folder? Would be cleaner and follow the repo standard for content.

2022-08-15 09:37 UTC, moritzkirstein approved these changes

2022-08-15 09:41 UTC, moritzkirstein requested changes
Code looks good. Noticed a minor issue in the preview, though: the `walletAddress` checkbox is acting in the opposite way somehow. When checked the value in the DDO preview is "false"
![grafik](https://user-images.githubusercontent.com/28757404/184613200-eabcc0af-8ddb-4a6e-8060-7fdd4cca357c.png)

2022-08-15 09:43 UTC, LucaMilanese90 commented
Can you please try again deleting the previously saved values from local storage? Just to understand if that is the cause or if it's unrelated

2022-08-15 09:45 UTC, moritzkirstein commented
Yes it is the issue. Works as expected with clean local storage.

2022-08-15 10:13 UTC, LucaMilanese90 commented
This might be a little problematic when we'll deploy. Maybe we should consider to put a time limit to decide if we want to use the values from local storage or show an empty form, does not make much sense to pre-fill a form with one week old data imho.

2022-08-15 17:01 UTC, moritzkirstein commented
> This might be a little problematic when we'll deploy. Maybe we should consider to put a time limit to decide if we want to use the values from local storage or show an empty form, does not make much sense to pre-fill a form with one week old data imho.

Not that big of a problem imo. For these values lets never use cached data. This is about user consenting they read terms / disclaimers, so we should request active input on every submit, anyways, if that makes sense.

2022-08-16 10:48 UTC, LucaMilanese90 commented
@moritzkirstein I updated the form to now exclude all the `<Terms />` values from local storage. This should fix all the problems.

2022-08-16 11:50 UTC, moritzkirstein approved these changes

2022-08-16 11:50 UTC, merged