feat: subpage edge computing [WIP]
deltaDAO/mvg-portal pull request #191
Opened 2022-08-19 09:30 UTC by LucaMilanese90

Fixes #185

## Proposed Changes

  - new "edge computing" page
  - explains the CtE concept in a brief section [WIP]

2022-09-05 14:18 UTC, moritzkirstein requested changes

2022-09-05 14:18 UTC, moritzkirstein commented on src/components/templates/Page.tsx
> +  isEdgeNetwork?: boolean
suggestion(blocking): I think `isEdgeNetwork` is a bit confusing. Maybe renaming this to `isEdgeProvider` makes more sense here? Would apply to all occurences.

2022-09-05 14:18 UTC, moritzkirstein commented on src/components/templates/Page.tsx
> +  isEdgeNetwork?: boolean
suggestion(blocking): I think `isEdgeNetwork` is a bit confusing. Maybe renaming this to `isEdgeProvider` makes more sense here? (Applies to all occurences)

2022-09-05 15:04 UTC, LucaMilanese90 commented on src/components/organisms/AssetContent/EdgeDetails.tsx
> +            />
Nice idea, I like it!

2022-09-05 15:05 UTC, LucaMilanese90 commented on src/components/organisms/AssetContent/index.tsx
> +    () => !!(ddo as EdgeDDO)?.findServiceByType('edge'),
You mean for the double `!!`?

2022-09-05 15:21 UTC, LucaMilanese90 commented on src/components/organisms/AssetContent/index.tsx
> +    () => !!(ddo as EdgeDDO)?.findServiceByType('edge'),
What if I just explicitly declare the type of the variable? Would that help in not needing the comment?

`const showEdgeDetails: boolean = useMemo(
    () => !!(ddo as EdgeDDO)?.findServiceByType('edge'),
    [ddo]
  )`

2022-09-06 10:03 UTC, moritzkirstein commented on src/components/organisms/AssetContent/index.tsx
> +    () => !!(ddo as EdgeDDO)?.findServiceByType('edge'),
I think it helps - let's use this for now

2022-09-06 10:07 UTC, moritzkirstein approved these changes

2022-09-06 10:23 UTC, merged