enhancement: menu ux update
deltaDAO/mvg-portal pull request #205
Opened 2022-08-31 17:29 UTC by LucaMilanese90

Fixes #201

## Proposed Changes

  - Move statistics to footer
  - Add Catalogue to navigation -> links to searchpage
  - Update ecosystems dropdown to display relevant projects
  - Move Profile to wallet dropdown (account dropdown)
  - Include Debug Mode (settings) in account dropdown
  - Include link to or setting to turn on Onboarding in account dropdown
  - Remove settings button

2022-09-01 11:27 UTC, moritzkirstein requested changes
- Log should be opened in a new tab
- Ecosystems should be opened in a new tab
- Statistics should be opened in a new tab
- Future Mobility should link to https://marketplace.future-mobility-alliance.org/

In general I am thinking if the `Log` entry makes sense in the top navigation or if this could/should be moved to the footer as well... We link to the exchangelog from every tsx anyways. Opinions?

2022-09-01 11:33 UTC, LucaMilanese90 commented
It seems a little bit too much to have it on the menu imho, but it's also true that our current footer is not that discoverable (small and low contrast, easy to miss if you are not actively looking for it). Another idea would be to create a dedicated page with all the links we want to add, we would have the space to properly explain what the link is and it would result in a single link in the menu

2022-09-01 11:55 UTC, moritzkirstein commented
Okay. Could be an apporach, I just fear the overhead this creates. We can think about updating the footer to be a bit more discoverable - smth like we did with the feat/mvp branch. If we manage to reuse components this could be managable effort and could be done anytime (not too high priority for now).

2022-09-01 12:00 UTC, LucaMilanese90 commented
Agreed, that footer was much better looking than the one we have right now for a relatively low implementation effort. But we should make sure everyone is fine with this, I remember Kai specifically mentioned that putting links in the footer is not a valid replacement for the the menubar, so before we move stuff around we should probably agree on the placement.

2022-09-01 14:31 UTC, moritzkirstein reviewed
![grafik](https://user-images.githubusercontent.com/28757404/187939493-2b0dfca6-ea1a-4670-88d3-4808721dd112.png)

Not yet that happy with this section. It looks a bit off to me. Maybe we can move the profile to the top? Or have the account info first and the profile in third position.
Also the "VIEW PROFILE" link itself could be more present imo, maybe coloring it differently will already help.
Currently I fear users miss this section and won't be able to find this if they are not used to the Web3 account addresses. Maybe we need a "account" icon to communicate this better.

2022-09-01 17:28 UTC, LucaMilanese90 commented
> The navbar is much more helpful now! Couple of suggestions:
> 
> - [ ]  Issue: External links should have some kind of indicator (like an icon) that they are pointing to an external resource
>  - [ ]  Issue: Hovering "Ecosystems" should automatically show the menu. I do not want to click it first.
>  - [ ]  Suggestion: Also, automatically show the menu when hovering over the account.
> - [ ] Suggestion: Remove the GX OCEAN section completely (they have to set up Metamask anyways)
> - [ ] Suggestion: "View Profile" should be the first entry in the account menu
> - [ ] Suggestion: Make "View Profile" the same dark blue color as the other links from the menu. Because it leads to a page and does not trigger a modal like other light blue links in the account menu

2022-09-02 10:45 UTC, LucaMilanese90 commented
Would something like this be ok for signaling an external link? 
<img width="517" alt="Screen Shot 2022-09-02 at 12 44 46" src="https://user-images.githubusercontent.com/20192135/188123399-3f32c265-b75b-4003-b1a4-596f31777319.png">

2022-09-02 11:38 UTC, moritzkirstein commented
In our privacy policy I think we have a symbol already for external links:
minimal-gaia-x.eu/privacy/en

2022-09-02 12:00 UTC, LucaMilanese90 commented
> In our privacy policy I think we have a symbol already for external links: https://minimal-gaia-x.eu/privacy/en#6-external-links Maybe we can (or should) just reuse this?
> 
> **Edit** seems like this was removed already. In that case I am fine with the symbol above, before that we used a small arrow symbol to the right of these links

It's still there, I just found it and added to the menubar

2022-09-02 12:04 UTC, moritzkirstein commented
Could also be added to `Statistics` in the footer

2022-09-02 13:53 UTC, moritzkirstein commented on src/components/molecules/Menu.tsx
> +import { Link, prefetchPathname } from 'gatsby'
question: seems like `prefetchPathname` is not used. Can the import be removed?

2022-09-02 13:54 UTC, moritzkirstein approved these changes

2022-09-02 16:34 UTC, merged