feat: update filters
deltaDAO/mvg-portal pull request #421
Opened 2023-09-27 09:52 UTC by LucaMilanese90

## Proposed Changes

  - update filter and sort logic
  - update filter and sort UI at `/search` and `/profile`

2023-10-03 21:16 UTC, moritzkirstein requested changes

2023-10-03 21:16 UTC, moritzkirstein commented on src/components/Search/Filter.tsx
> +  },
suggestion: keeping these here makes sense imo, as we probably want these as default filters for every portal (see below)

2023-10-03 21:16 UTC, moritzkirstein commented on src/components/Search/Filter.tsx
> +  }
suggestion: for custom filters I would suggest setting up a config file, similar to the address.config file
e.g., `filters.config.js`
Would be easy to quickly change / setup filters for every portal that way

2023-10-03 21:16 UTC, moritzkirstein commented on src/components/Search/Filter.tsx
> +}
suggestion: the same applies for these set definitions

maybe a config file just to specify filter-sets makes sense at that point (`const filterSets` and `id: 'filterSet'` could be moved there)

2023-10-03 21:16 UTC, moritzkirstein commented on src/components/Search/Filter.tsx
> +    }
suggestion: we can use early return pattern here

2023-10-03 21:16 UTC, moritzkirstein commented on src/components/Search/Filter.tsx
> +    if (addFiltersToUrl) {
suggestion: early return could be used here, too

2023-10-03 21:16 UTC, moritzkirstein commented on src/components/Search/Filter.tsx
> +  async function applyClearFilter(addFiltersToUrl: boolean) {
suggestion: just naming this `clearFilters` is maybe a bit easier for readability.

2023-10-03 21:16 UTC, moritzkirstein commented on src/components/Search/sort.tsx
> +  { display: '\u2193 Desc', value: SortDirectionOptions.Descending }
suggestion: I'd prefer spelling out "Ascending" / "Descending" respectively

2023-10-04 08:57 UTC, LucaMilanese90 commented on src/@hooks/useDebounce.tsx
> +  const callback = useCallback(effect, dependencies)
I also tried this in the first iteration but it was causing an infinite loop so I took it out. Not really sure why it happens tbh.

2023-10-04 14:08 UTC, oceanByte commented on src/@hooks/useDebounce.tsx
> +  const callback = useCallback(effect, dependencies)
Fine for now, but we should circle back to this when @moritzkirstein returns to address it properly.

2023-10-04 14:09 UTC, oceanByte approved these changes

2023-10-04 14:10 UTC, LucaMilanese90 commented on src/@hooks/useDebounce.tsx
> +  const callback = useCallback(effect, dependencies)
I'll open an issue

2023-10-04 14:10 UTC, oceanByte approved these changes

2023-10-04 14:10 UTC, merged